### PR TITLE
Added 'prompted' command to make the bot respond whenever its name is mentioned

### PR DESCRIPTION
**Pull request by bolecki**
Hello!  I added a new command that will cause the bot to respond every time a message contains its name.  This will override the default behavior of doubling the replyrate.

Thanks!

### CODE REVIEW

**Comment by bolecki** [comment]
I will submit another pull request from a proper branch.

Thanks!

**Comment by bdrewery** [comment]
Just set the replyrate to 100. Should achieve the same thing, as your code even does!

**Comment by bolecki** [comment]
I was looking for an easy way to turn the feature on and off without restarting the script.  I have been using this in my own bot for a while now.  Do you think this would be a useful feature if I submit another pull request in a separate branch?

**Comment by bdrewery** [comment]
You can message the bot with:
`!replyrate 3`
`!replyrate 100`

**Comment by bolecki** [comment]
I believe that would make the bot respond to any message.  The prompted flag would cause the bot to only respond if the message contains its name.

**Comment by bdrewery** [comment]
Oh, right. Sounds useful.

**Comment by bolecki** [comment]
Awesome!  I will submit another pull request soon.  Thanks!

**Pull request closed without merging**
